apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
  annotations:
    pod-url: http://mysite.com/nginx-pod
    supported: 1-888-222-13000
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "500m"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      ports:
        - containerPort: 80