apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        httpGet:
          path: /healthy
          port: 80
        initialDelaySeconds: 5
        timeOutSeconds: 1
        periodSeconds: 5
        failureThreshold: 3
  resources:
    requests:
      cpu: "500m"
      memory: "64Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
    ports:
      - containerPot: 80