apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
  annotations:
    pod-url: http://mysite.com/nginx-pod
    supported-by: 1-800-222-3300
spec:
  containers:
    - name: nginx
      image: nginx:1.3.6
      ports:
        - containerPort: 80