apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test
  annotations:
    description: A pod with hostPath volume type.
spec:
  volumes:
    - name: docker-sock
      hostPath:
        hostPath: /var/run/docker.sock
        type: Socket
  containers:
    - name: ubuntu
      image: ubuntu:16.04
      command: ["/bin/bash", "-c", "--"]
      args: [ "while true; do sleep 10; done;" ]
      mountVolumes:
        - mountPath: /var/run/docker.sock
          name: docker-sock
